---

- name: Download package
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm"
    dest: /tmp/vector-{{ vector_version }}.deb
    mode: "0400"

- name: Install package
  ansible.builtin.apt:
    deb: /tmp/vector-{{ vector_version }}.deb
    state: present
